version: 2
jobs:
  noop:
    machine: true
    steps:
      - run: exit 0

workflows:
  version: 2
  noop:
    jobs:
      - noop:
          filters:
            branches:
              ignore: gh-pages
