version: 2
jobs:
  test:
    docker:
      - image: ymtszw/elm_for_ci:0.19
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Revision }}
            - repo-{{ .Branch }}-
            - repo-
      - checkout
      - run: elm-test
      - save_cache:
          paths:
            - ~/.elm
          key: repo-{{ .Branch }}-{{ .Revision }}
  compile_pattern_lab:
    docker:
      - image: ymtszw/elm_for_ci:0.19
    working_directory: ~/repo
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Revision }}
      - checkout
      - run: elm make src/View/PatternLab.elm --output=index.html
  deploy:
    docker:
      - image: ymtszw/elm_for_ci:0.19
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ca:ab:40:08:08:7e:38:57:80:73:a3:03:ee:2c:0a:42"
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Revision }}
      - checkout
      - run: make release
      - run: git checkout zephyr-app || { git fetch origin zephyr-app && git checkout zephyr-app; }
      - run: cp -vr dist/* .
      - run: git add -A .
      - run: git -c user.email=ymtszw@gmail.com -c user.name=ymtszw commit -m "[CI] Build release" || echo "Nothing to commit."
      - run: git push origin HEAD:zephyr-app
      - run: git push git@github.com:zephyr-app/zephyr-app.github.io.git HEAD:master

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - compile_pattern_lab:
          requires:
            - test
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - test
            - compile_pattern_lab
          filters:
            branches:
              only: master
